### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by Fusecchi** [Fusecchi/ExcelInteropGUI#1]
## To-Do List

 - [x] Make edit windows editable to excel.
 - [x] Transfer the data to another file.
 - [x] Applicable on CSV data (Send)
 - [x] Make progress bar for the application.
 - [x] Figure out how to process other data.
 - [x] Make preset for other uses. 
 - [x] Clear/Reset Everything
 - [x] Save the edited data back into CSV
 - [x] Automatically rename file and make duplicate
 - [x] Able to recognize both files
 - [x] Rollback
 - [x] Change Language
